n_dim: 64
n_head: 1
num_layer_encoder: 1
num_layer_decoder: 1
gamma: 0.99
tau: 0.95
clip: 0.05
lr: 5e-4
eps: 1e-5
entropy_coef: 0.01
map_name: "6h_vs_8z"
n_steps: 1e7
max_grad_norm: 10
huber_delta: 10.0
n_ppo_update: 15
time_horizon: 100
n_env: 32
version: 1
