n_dim: 64
n_head: 1
num_layer_encoder: 1
num_layer_decoder: 1
gamma: 0.99
tau: 0.95
clip: 0.05
lr: 5e-5
eps: 1e-5
entropy_coef: 0.001
env_name: mamujoco
train_seed: 1024
eval_seed: 1024
env_args:
    scenario: Ant-v2
    agent_conf: 8x1
    agent_obsk: 0 # We use the fully observable setting, so this argument is not useful. But we still keep it.
    episode_limit: 1000
n_steps: 15e6
max_grad_norm: 0.5
huber_delta: 10.0
n_ppo_update: 10
time_horizon: 100
n_train_env: 40
n_eval_env: 50
map_name: Ant-v2-8x1
discrete: False
n_eval_eps: 200