n_dim: 64
n_head: 1
num_layer_encoder: 1
num_layer_decoder: 1
gamma: 0.99
tau: 0.95
clip: 0.05
lr: 5e-4
eps: 1e-5
entropy_coef: 0.01
env_name: football
train_seed: 1024
eval_seed: 1024
env_args:
    env_name: academy_pass_and_shoot_with_keeper
    stacked: False
    representation: simple115v2
    rewards: scoring,checkpoints
    write_goal_dumps: False
    write_full_episode_dumps: False
    render: False
    write_video: False
    dump_frequency: 1
    logdir: ~
    extra_players: ~
    number_of_left_players_agent_controls: 2 # has to be consistent with the default setting below
    number_of_right_players_agent_controls: 0
    channel_dimensions:
      - 96
      - 72
    other_config_options: ~
n_steps: 2e6
max_grad_norm: 0.5
huber_delta: 10.0
n_ppo_update: 10
time_horizon: 200
n_train_env: 20
n_eval_env: 50
map_name: HalfCheetah-v2
discrete: True
n_eval_eps: 200

# env_num_agents (for REFERENCE):
#   "academy_pass_and_shoot_with_keeper": 2,
#   "academy_run_pass_and_shoot_with_keeper": 2,
#   "academy_3_vs_1_with_keeper": 3,
#   "academy_counterattack_easy": 4,
#   "academy_counterattack_hard": 4,
#   "academy_corner": 11,
#   "academy_single_goal_versus_lazy": 11